### ISSUE TITLE
Add explanations for use and opt out to all setup script steps

### ISSUE THREAD

**Issue by singhprd** [fac/fa-initial-machine-setup#3]
- [x] Add explanation for all steps so that newer engineers know why a tool is used and how to troubleshoot/customise it in the future
- [ ] Add opt out so that steps can be skipped

**Comment by dgholz** [comment]
First part done in #14, second part done by making steps idempotent (in this phase 1 of machine setup, all the steps should run every time and configure the machine, none are skippable)
